//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookstore.View
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("Authorization")]
    public partial class Authorization
    {
        public int id { get; set; }
        public int id_employee { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public bool is_deleted { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
