//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookstore.View
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Books()
        {
            this.book_reservation = new HashSet<book_reservation>();
            this.promotion_on_Books = new HashSet<promotion_on_Books>();
            this.selling = new HashSet<selling>();
            this.write_offs = new HashSet<write_offs>();
        }
    
        public int id { get; set; }
        public string name_book { get; set; }
        public int id_Author { get; set; }
        public int id_pub_house { get; set; }
        public int year_publishing { get; set; }
        public int id_genre { get; set; }
        public int number_pages { get; set; }
        public int cost_price { get; set; }
        public int selling_price { get; set; }
        public int amount { get; set; }
        public bool is_deleted { get; set; }
    
        public virtual Author Author { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<book_reservation> book_reservation { get; set; }
        public virtual publishing_house publishing_house { get; set; }
        public virtual Genres Genres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<promotion_on_Books> promotion_on_Books { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<selling> selling { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<write_offs> write_offs { get; set; }
    }
}
