//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookstore.View
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbBookstore : DbContext
    {
        private static DbBookstore _context;
        public DbBookstore()
            : base("name=DbBookstore")
        {
        }

        public static DbBookstore GetContext()
        {
            if(_context == null) 
                _context = new DbBookstore();

            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Author> Author { get; set; }
        public virtual DbSet<Authorization> Authorization { get; set; }
        public virtual DbSet<book_reservation> book_reservation { get; set; }
        public virtual DbSet<Books> Books { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Genres> Genres { get; set; }
        public virtual DbSet<Human> Human { get; set; }
        public virtual DbSet<job_titles> job_titles { get; set; }
        public virtual DbSet<promotion_on_Books> promotion_on_Books { get; set; }
        public virtual DbSet<promotions> promotions { get; set; }
        public virtual DbSet<publishing_house> publishing_house { get; set; }
        public virtual DbSet<selling> selling { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<write_offs> write_offs { get; set; }
    }
}
