//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookstore.View
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("book_reservation")]
    public partial class book_reservation
    {
        public int id { get; set; }
        public int id_book { get; set; }
        public int id_user { get; set; }
        public int amount { get; set; }
        public bool is_redeem { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual users users { get; set; }
    }
}
