//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bookstore.View
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbBookstoreEntities : DbContext
    {
        private static DbBookstoreEntities _context;
        public DbBookstoreEntities()
            : base("name=DbBookstoreEntities")
        {
        }

        public static DbBookstoreEntities GetContext()
        {
            if(_context == null)
                _context = new DbBookstoreEntities();

            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<author> author { get; set; }
        public virtual DbSet<authorization> authorization { get; set; }
        public virtual DbSet<book_reservation> book_reservation { get; set; }
        public virtual DbSet<books> books { get; set; }
        public virtual DbSet<employees> employees { get; set; }
        public virtual DbSet<genres> genres { get; set; }
        public virtual DbSet<human> human { get; set; }
        public virtual DbSet<job_titles> job_titles { get; set; }
        public virtual DbSet<promotion_on_books> promotion_on_books { get; set; }
        public virtual DbSet<promotions> promotions { get; set; }
        public virtual DbSet<publishing_house> publishing_house { get; set; }
        public virtual DbSet<selling> selling { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<write_offs> write_offs { get; set; }
    }
}
