//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookstore.View
{
    using System;
    using System.Collections.Generic;
    
    public partial class promotion_on_Books
    {
        public int id { get; set; }
        public int id_book { get; set; }
        public int id_promotion { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual promotions promotions { get; set; }
    }
}
