//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.View.MVVM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class book_reservation
    {
        public int id { get; set; }
        public int id_book { get; set; }
        public int id_user { get; set; }
        public int amount { get; set; }
        public bool is_redeem { get; set; }
    
        public virtual book book { get; set; }
        public virtual user user { get; set; }
    }
}
