//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.View.MVVM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbBookStoreEntities : DbContext
    {
        private static DbBookStoreEntities _context;
        public DbBookStoreEntities()
            : base("name=DbBookStoreEntities")
        {
        }

        public static DbBookStoreEntities GetContext()
        {
            if( _context == null )
                _context = new DbBookStoreEntities();

            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<author> authors { get; set; }
        public virtual DbSet<authorization> authorizations { get; set; }
        public virtual DbSet<book_reservation> book_reservation { get; set; }
        public virtual DbSet<book> books { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<genre> genres { get; set; }
        public virtual DbSet<human> humen { get; set; }
        public virtual DbSet<job_titles> job_titles { get; set; }
        public virtual DbSet<promotion_on_books> promotion_on_books { get; set; }
        public virtual DbSet<promotion> promotions { get; set; }
        public virtual DbSet<publishing_house> publishing_house { get; set; }
        public virtual DbSet<selling> sellings { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<write_offs> write_offs { get; set; }
    }
}
