//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.View.MVVM.Models
{

    public partial class selling
    {
        public int id { get; set; }
        public int id_book { get; set; }
        public int id_employee { get; set; }
        public System.DateTime date_write_offs { get; set; }
    
        public virtual book book { get; set; }
        public virtual employee employee { get; set; }
    }
}
